# Generated by Django 4.1 on 2022-09-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(help_text='User ID', primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('authority', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
