# Generated by Django 4.1 on 2022-12-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doc_idx',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_admission',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='room',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
