# Generated by Django 4.1 on 2022-08-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_user_managers_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='alias',
        ),
    ]
