# Generated by Django 4.1 on 2022-12-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_patient_doc_idx_alter_patient_is_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='patient', max_length=50),
        ),
    ]
