# Generated by Django 4.1 on 2022-08-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_rename_username_user_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='username',
        ),
    ]
